spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "rootroot"

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug